name: '[autorelease] On release published'

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Download nupkg release asset
      uses: robinraju/release-downloader@v1.9
      with:
        releaseId: '${{ github.event.release.id }}'
        fileName: "*.nupkg"
        out-file-path: 'assets'

    - name: Publish NuGet package
      run: |
        for file in assets/*.nupkg; do 
          dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json
        done